### ISSUE TITLE
LuaCoderAssist Crash

### ISSUE THREAD

**Issue by datavisorchengpeng** [liwangqian/LuaCoderAssist#104]
```
[Info  - 2:48:16 PM] coder inited
[Info  - 2:48:16 PM] extension initialize status: true
[Info  - 2:48:16 PM] Connection to server got closed. Server will restart.
[Info  - 2:48:17 PM] coder inited
[Info  - 2:48:17 PM] extension initialize status: true
[Info  - 2:48:17 PM] Connection to server got closed. Server will restart.
[Error - 2:48:17 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/Users/ellutionist/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
[Info  - 2:48:17 PM] coder inited
[Info  - 2:48:17 PM] extension initialize status: true
[Info  - 2:48:18 PM] Connection to server got closed. Server will restart.
[Info  - 2:48:18 PM] coder inited
[Info  - 2:48:18 PM] extension initialize status: true
[Info  - 2:48:19 PM] Connection to server got closed. Server will restart.
[Info  - 2:48:19 PM] coder inited
[Info  - 2:48:19 PM] extension initialize status: true
[Error - 2:48:19 PM] Connection to server got closed. Server will not be restarted.
```

This happens every time the VS code launches.

Version: v2.3.9
OS: Mac OS

**Comment by liwangqian** [comment]
maybe you can refer to this issue https://github.com/liwangqian/LuaCoderAssist/issues/95
