### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by isshe** [liwangqian/LuaCoderAssist#112]
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Socket.Writable.end (internal/streams/writable.js:567:10)
    at Socket.end (net.js:591:31)
    at /root/.vscode-server/extensions/liwangqian.luacoderassist-2.3.9/server/providers/diagnostic-provider.js:109:24
    at new Promise (<anonymous>)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[Info  - 9:01:09 PM] Connection to server got closed. Server will restart.
```
你好，请问这个是什么问题呢？

**Comment by isshe** [comment]
装了 2.5.0 然后装了 luacheck 后解决了
