### ISSUE TITLE
Extension crashing

### ISSUE THREAD

**Issue by NullCascade** [liwangqian/LuaCoderAssist#59]
vscode is complaining that this extension is crashing, with the following log:

```
[Info  - 11:42:56 AM] coder inited
[Info  - 11:42:56 AM] extension initialize status: true
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at fs.read (fs.js:2167:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)
[Info  - 11:43:09 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:11 AM] coder inited
[Info  - 11:43:11 AM] extension initialize status: true
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at fs.read (fs.js:2167:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)
[Info  - 11:43:11 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:12 AM] coder inited
[Info  - 11:43:12 AM] extension initialize status: true
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at fs.read (fs.js:2167:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)
[Info  - 11:43:12 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:12 AM] coder inited
[Info  - 11:43:12 AM] extension initialize status: true
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at fs.read (fs.js:2167:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)
[Info  - 11:43:12 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:13 AM] coder inited
[Info  - 11:43:13 AM] extension initialize status: true
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at fs.read (fs.js:2167:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)
[Error - 11:43:13 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by liwangqian** [comment]
seems has no access to the directory？
