### ISSUE TITLE
Latest LuaCoderAssistCrash

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#93]
```txt
[Info  - 10:34:58 PM] coder inited
[Info  - 10:34:58 PM] extension initialize status: true
[Info  - 10:34:59 PM] loading STD library ...
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at internal/fs/streams.js:173:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[Info  - 10:34:59 PM] loading LOVE library ...
[Info  - 10:34:59 PM] Connection to server got closed. Server will restart.
[Error - 10:34:59 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
[Info  - 10:35:00 PM] coder inited
[Info  - 10:35:00 PM] extension initialize status: true
[Info  - 10:35:00 PM] loading STD library ...
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at internal/fs/streams.js:173:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[Info  - 10:35:01 PM] loading LOVE library ...
[Info  - 10:35:01 PM] search /usr/local/share/lua/5.2 begin.
[Info  - 10:35:01 PM] Connection to server got closed. Server will restart.
[Error - 10:35:01 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
[Info  - 10:35:01 PM] coder inited
[Info  - 10:35:01 PM] extension initialize status: true
[Info  - 10:35:02 PM] loading STD library ...
[Info  - 10:35:02 PM] loading LOVE library ...
[Info  - 10:35:02 PM] search /usr/local/share/lua/5.2 begin.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at internal/fs/streams.js:173:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[Info  - 10:35:02 PM] search /home/nexela/Develop/cpp/Factorio/data/core/lualib begin.
[Info  - 10:35:02 PM] Connection to server got closed. Server will restart.
[Error - 10:35:02 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
[Info  - 10:35:03 PM] coder inited
[Info  - 10:35:03 PM] extension initialize status: true
[Info  - 10:35:03 PM] loading STD library ...
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at internal/fs/streams.js:173:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[Info  - 10:35:03 PM] loading LOVE library ...
[Info  - 10:35:03 PM] Connection to server got closed. Server will restart.
[Error - 10:35:03 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/nexela/.vscode/extensions/liwangqian.luacoderassist-2.3.9/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
[Info  - 10:35:04 PM] coder inited
[Info  - 10:35:04 PM] extension initialize status: true
[Info  - 10:35:04 PM] loading STD library ...
[Info  - 10:35:04 PM] loading LOVE library ...
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at internal/fs/streams.js:173:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
[Info  - 10:35:04 PM] search /usr/local/share/lua/5.2 begin.
[Error - 10:35:04 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by Nexela** [comment]
Possibly related to setting "LuaCoderAssist.luaPath" incorrectly.

**Comment by liwangqian** [comment]
So, your problem got resolved?

**Comment by Nexela** [comment]
Yes. It was related to a typo in "LuaCoderAssist.luaPath"
