### ISSUE TITLE
Typing 'setmetatable' function gives error at console

### ISSUE THREAD

**Issue by MikuAuahDark** [liwangqian/LuaCoderAssist#99]
Typing
```lua
setmetatable(
```
Is enough to trigger error. This printed at the console:
```
[Error - 14.40.27] TypeError: Cannot read property 'type' of undefined
    at parseSetmetatable (c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:422:26)
    at parseInitStatement (c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:95:26)
    at c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:448:13
    at Array.forEach (<anonymous>)
    at parseReturnStatement (c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:447:24)
    at walkNode (c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:536:17)
    at Array.forEach (<anonymous>)
    at walkNodes (c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:499:15)
    at parseScopeStatement (c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:437:9)
    at walkNode (c:\Users\MikuAuahDark\.vscode\extensions\liwangqian.luacoderassist-2.3.9\server\lib\engine\core.js:527:17)
```

This error is annoying as it always error until it's closed with matching `)`.

**Comment by liwangqian** [comment]
well，thanks for your feedback, and this will be fixed the next release.

**Comment by MikuAuahDark** [comment]
If you could check #51 I'd highly appreciate it, thank you.
